"""Declarative provisioning of VideoIPath devices through the existing SDK apps.

Blueprints are reusable configuration templates within this provisioning layer.

A standalone feature: construct :class:`ProvisioningEngine` with an app (``ProvisioningEngine(app)``),
describe a device with :class:`ProvisioningDevice`, then pass a YAML file path or :class:`Blueprint` to
``engine.plan(...)`` (read-only preview) and ``plan.apply()``, or ``engine.apply(...)`` in one call.
``VideoIPathApp`` neither imports nor exposes this package.

Importing this package and loading blueprints never connects to a server.
"""

from __future__ import annotations

from videoipath_automation_tool.provisioning.engine import ProvisioningApp, ProvisioningEngine, ProvisioningPlan
from videoipath_automation_tool.provisioning.errors import (
    InventoryNotReadyError,
    ProcessorInputError,
    ProvisioningApplyError,
    ProvisioningCapabilityError,
    ProvisioningConflictError,
    ProvisioningError,
    ProvisioningTargetError,
    ProvisioningValidationError,
    TopologyNotReadyError,
    ValidationIssue,
)
from videoipath_automation_tool.provisioning.inputs import InputDefinition, InputReference, LiteralValue
from videoipath_automation_tool.provisioning.models import (
    AlternativeAddress,
    ApplyOptions,
    ApplyResult,
    Blueprint,
    BlueprintConfiguration,
    CatalogId,
    ConnectionState,
    Coordinates,
    Credentials,
    DevicePatch,
    DeviceTarget,
    Diagnostic,
    EdgePatch,
    EndpointIdentity,
    FieldChange,
    InterfaceBinding,
    InventorySettings,
    ModulePatch,
    ModuleTarget,
    PeerEndpoint,
    PhaseResult,
    PlannedOperation,
    PlannedPhase,
    PortBinding,
    PortSelector,
    ProcessorResult,
    ProvisioningConnection,
    ProvisioningDevice,
    TagDelta,
    VertexEdit,
    VertexPatch,
)
from videoipath_automation_tool.provisioning.naming import (
    DEFAULT_NAMING,
    Field,
    Join,
    NameContext,
    NameRenderer,
    NamingScheme,
    Text,
)
from videoipath_automation_tool.provisioning.processors import (
    DeviceRecord,
    DriverContext,
    ModuleRecord,
    PortRecord,
    ProcessingContext,
    ProcessorRegistry,
    SourceFacts,
    VertexProcessor,
    VertexRecord,
)
from videoipath_automation_tool.provisioning.processors.matrox import MatroxConvertIPParams, MatroxConvertIPProcessor
from videoipath_automation_tool.provisioning.resolution import published_json_schema

__all__ = [
    "DEFAULT_NAMING",
    "AlternativeAddress",
    "ApplyOptions",
    "ApplyResult",
    "Blueprint",
    "BlueprintConfiguration",
    "CatalogId",
    "ConnectionState",
    "Coordinates",
    "Credentials",
    "DevicePatch",
    "DeviceRecord",
    "DeviceTarget",
    "Diagnostic",
    "DriverContext",
    "EdgePatch",
    "EndpointIdentity",
    "Field",
    "FieldChange",
    "InputDefinition",
    "InputReference",
    "InterfaceBinding",
    "InventoryNotReadyError",
    "InventorySettings",
    "Join",
    "LiteralValue",
    "MatroxConvertIPParams",
    "MatroxConvertIPProcessor",
    "ModulePatch",
    "ModuleRecord",
    "ModuleTarget",
    "NameContext",
    "NameRenderer",
    "NamingScheme",
    "PeerEndpoint",
    "PhaseResult",
    "PlannedOperation",
    "PlannedPhase",
    "PortBinding",
    "PortRecord",
    "PortSelector",
    "ProcessingContext",
    "ProcessorInputError",
    "ProcessorRegistry",
    "ProcessorResult",
    "ProvisioningApp",
    "ProvisioningApplyError",
    "ProvisioningCapabilityError",
    "ProvisioningConflictError",
    "ProvisioningConnection",
    "ProvisioningDevice",
    "ProvisioningEngine",
    "ProvisioningError",
    "ProvisioningPlan",
    "ProvisioningTargetError",
    "ProvisioningValidationError",
    "SourceFacts",
    "TagDelta",
    "Text",
    "TopologyNotReadyError",
    "ValidationIssue",
    "VertexEdit",
    "VertexPatch",
    "VertexProcessor",
    "VertexRecord",
    "published_json_schema",
]
