name: Build and Upload Python Package
# Note: This is a temporary workflow for the repository in a private state.
# Before making the repository public, it will be replaced!

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Extract package version
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Build package
        run: poetry build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with: 
          name: videoipath-automation-tool-${{ env.VERSION }}
          path: dist/*
